# Generated by Django 4.2.20 on 2025-03-14 07:41

from django.db import migrations, models
import django.utils.timezone
import promotions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.JSONField(blank=True, default=dict, null=True)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('minimum_cart_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('active_from', models.DateTimeField()),
                ('expire_at', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('target', models.PositiveIntegerField(blank=True, null=True)),
                ('is_approve', models.BooleanField(default=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=promotions.models.default_translated_languages, null=True)),
                ('shop_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=50)),
                ('image', models.JSONField(blank=True, default=dict, null=True)),
                ('cover_image', models.JSONField(blank=True, default=dict, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=promotions.models.default_translated_languages, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
