# Generated by Django 4.2.20 on 2025-03-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_baseuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
