# Generated by Django 4.2.20 on 2025-03-14 05:16

from django.db import migrations, models
import layouts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('faq_description', models.TextField()),
                ('faq_type', models.CharField(blank=True, default='global', max_length=55, null=True)),
                ('issued_by', models.CharField(blank=True, default='Super Admin', max_length=25, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=layouts.models.default_translated_languages, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, default='global', max_length=55, null=True)),
                ('issued_by', models.CharField(blank=True, default='Super Admin', max_length=25, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=layouts.models.default_translated_languages, null=True)),
            ],
        ),
    ]
