# Generated by Django 4.2.20 on 2025-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('banners', models.JSONField(blank=True, default=list, null=True)),
                ('promotional_sliders', models.JSONField(blank=True, default=list, null=True)),
                ('icon', models.CharField(blank=True, default='default_icon', max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=list, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
