# Generated by Django 4.2.20 on 2025-03-13 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
