# Generated by Django 4.2.20 on 2025-03-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
