# Generated by Django 4.2.20 on 2025-03-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_manufacturer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.type'),
        ),
    ]
