# Generated by Django 4.2.20 on 2025-03-14 04:11

from django.db import migrations, models
import django.utils.timezone
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_manufacturer_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=products.models.default_translated_languages, null=True)),
                ('products_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(max_length=50)),
                ('image', models.JSONField(blank=True, default=dict, null=True)),
                ('cover_image', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
