# Generated by Django 4.2.20 on 2025-03-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
    ]
