# Generated by Django 4.2.20 on 2025-03-14 06:30

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_author_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='translated_languages',
            field=models.JSONField(blank=True, default=products.models.default_translated_languages, null=True),
        ),
    ]
